### ISSUE TITLE
[Feature Request] PWA Support

### ISSUE THREAD

**Issue by axmad386** [kodepintar/colorful-quran#58]
It will be awesome if we can install this app via pwa support. 
# Todo
- [x] set manifest correctly with icons
- [x] set service-worker (offline mode)
- [x] make sure PWA is installable

**Comment by axmad386** [comment]
Already impelemented
